Fix Broken null-check for client.id
Adding the group broke the client.id logic when no client.id configured.

`EnableKafkaIntegrationTests`...

13:51:01.196 WARN  [main][org.apache.kafka.common.utils.AppInfoParser] Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=null-0